// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLg4Qserw1_gTpmh1AxqubC3g--ljOXlo',
    appId: '1:1013782615021:web:2c4b4bc56c5dd020ee0de4',
    messagingSenderId: '1013782615021',
    projectId: 'laporin-7c61e',
    authDomain: 'laporin-7c61e.firebaseapp.com',
    storageBucket: 'laporin-7c61e.firebasestorage.app',
    measurementId: 'G-FJTE71NGBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc7g9x4PwPk2v5R7KqSR1uxf8X3OmV2No',
    appId: '1:1013782615021:android:10da62e4537cf56eee0de4',
    messagingSenderId: '1013782615021',
    projectId: 'laporin-7c61e',
    storageBucket: 'laporin-7c61e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXg126nt--mA060kg5V2l8rBnn0jqWBXQ',
    appId: '1:1013782615021:ios:d6921f0d47277867ee0de4',
    messagingSenderId: '1013782615021',
    projectId: 'laporin-7c61e',
    storageBucket: 'laporin-7c61e.firebasestorage.app',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXg126nt--mA060kg5V2l8rBnn0jqWBXQ',
    appId: '1:1013782615021:ios:d6921f0d47277867ee0de4',
    messagingSenderId: '1013782615021',
    projectId: 'laporin-7c61e',
    storageBucket: 'laporin-7c61e.firebasestorage.app',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLg4Qserw1_gTpmh1AxqubC3g--ljOXlo',
    appId: '1:1013782615021:web:0b59ecd5bd9b6270ee0de4',
    messagingSenderId: '1013782615021',
    projectId: 'laporin-7c61e',
    authDomain: 'laporin-7c61e.firebaseapp.com',
    storageBucket: 'laporin-7c61e.firebasestorage.app',
    measurementId: 'G-XLQZWD4FCV',
  );
}